// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearDownloaders():Promise<void>;

export function DownloadList(arg1:Array<number>):Promise<void>;

export function GetBookInfo():Promise<main.BookInfo>;

export function GetComicChapter():Promise<Array<main.ChapterInfo>>;

export function GetDownloader(arg1:string):Promise<void>;

export function GetDownloaders():Promise<Array<main.DownloaderSingle>>;

export function ProcessSend():Promise<void>;

export function Search(arg1:string,arg2:number):Promise<Array<main.Comic>>;
