// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDownloaders() {
  return window['go']['main']['DownloaderManager']['ClearDownloaders']();
}

export function DownloadList(arg1) {
  return window['go']['main']['DownloaderManager']['DownloadList'](arg1);
}

export function GetBookInfo() {
  return window['go']['main']['DownloaderManager']['GetBookInfo']();
}

export function GetComicChapter() {
  return window['go']['main']['DownloaderManager']['GetComicChapter']();
}

export function GetDownloader(arg1) {
  return window['go']['main']['DownloaderManager']['GetDownloader'](arg1);
}

export function GetDownloaders() {
  return window['go']['main']['DownloaderManager']['GetDownloaders']();
}

export function ProcessSend() {
  return window['go']['main']['DownloaderManager']['ProcessSend']();
}

export function Search(arg1, arg2) {
  return window['go']['main']['DownloaderManager']['Search'](arg1, arg2);
}
